name: Update Site & Config

on:
  push:
    paths:
      - 'links.json'
      - 'radio/**'
      - 'assets/**'
      - 'index.html'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Repository Checkout
        uses: actions/checkout@v4

      - name: ğŸ•’ Update Timestamp
        run: |
          echo "Last updated: $(date)" > last_build_info.txt

      - name: ğŸŒ Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ğŸŒ â€¢ Seite autom. aktualisiert!"
          file_pattern: '.'
          skip_dirty_check: false